-- Contiene tabla e inserciones de clase

CREATE TABLE clase (
    ID_CLASE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_CLASE VARCHAR(100) NOT NULL,
    DURACION_CLASE VARCHAR(20) NOT NULL,
    NUM_DOC_ENTRENADOR VARCHAR(15) NOT NULL,
    FOREIGN KEY (NUM_DOC_ENTRENADOR) REFERENCES entrenador(NUM_DOC_ENTRENADOR)
);

INSERT INTO clase (
    NOMBRE_CLASE, DURACION_CLASE, NUM_DOC_ENTRENADOR
) VALUES
('Yoga', '30', 1000948516),
('Aerobicos', '60', 1012987158),
('Pilates', '45', 1000948516);
