-- Contiene tabla e inserciones de fisioterapeuta

CREATE TABLE fisioterapeuta (
    NUM_DOC_FISIOTERAPEUTA VARCHAR(15) PRIMARY KEY,
    NOMBRE_FISIOTERAPEUTA VARCHAR(100) NOT NULL,
    CORREO_FISIOTERAPEUTA VARCHAR(100) NOT NULL,
    ESTADO_FISIOTERAPEUTA VARCHAR(20) NOT NULL,
    NUM_TELEFONO_FISIOTERAPEUTA VARCHAR(15) NOT NULL,
    TURNO_FISIOTERAPEUTA VARCHAR(20) NOT NULL,
    ANIOS_EXP_FISIOTERAPEUTA INT,
    ESPECIALIDAD_FISIOTERAPEUTA VARCHAR(100) NOT NULL,
    NUM_LICENCIA_FISIOTERAPEUTA VARCHAR(15) NOT NULL
);

INSERT INTO fisioterapeuta (
    NUM_DOC_FISIOTERAPEUTA, NOMBRE_FISIOTERAPEUTA, CORREO_FISIOTERAPEUTA,
    ESTADO_FISIOTERAPEUTA, NUM_TELEFONO_FISIOTERAPEUTA, TURNO_FISIOTERAPEUTA,
    ANIOS_EXP_FISIOTERAPEUTA, ESPECIALIDAD_FISIOTERAPEUTA, NUM_LICENCIA_FISIOTERAPEUTA
) VALUES
(1012154853, 'Andrés Gómez', 'andres.gomez@gymfit.com', 'Activo', 3157896541, 'Mañana', 6, 'Deportiva', 12345),
(1000154762, 'Sofía Torres', 'sofia.torres@gymfit.com', 'Activo', 3194561230, 'Tarde', 4, 'Neurologica', 23456);

